### ISSUE TITLE
Empty {get:parameter} Variable Returns Tag as String

### ISSUE THREAD

**Issue by kgrote** [rsanchez/mo_variables#51]
I have a query string with 2 possible parameters, both are optional:

`http://mysite.com?industry=21&type=brochures`

And I'm using these to populate my `{channel:entries}` tag:

`{exp:channel:entries channel='{get:type}' category='{get:industry}'}`

But if I just have an `industry` parameter and no `type` parameter, instead of returning an empty string Mo' Variables will return the tag in plain text:

`http://mysite.com?industry=21`

Expected Result:
`{exp:channel:entries channel='' category='21'}`

Current Result:
`{exp:channel:entries channel='{get:type}' category='21'}`

**Comment by rsanchez** [comment]
If you go into the Mo' Variables extension settings, you can set default values for `{get:}` variables. So you'd add `type:` to the settings to ensure it gets parsed with a blank value if it's not present in the query string.
